### ISSUE TITLE
IDP?

### ISSUE THREAD

**Issue by diminoten** [jayjzheng/ff_rankings#12]
What LoE would it be to add in IDP?  Not exactly sure when to draft Watt!

**Comment by diminoten** [comment]
Just casually perusing the code, it's more complicated than adding 'IDP' to `services/rankings.js`, yes?  If not, I can just do that locally, no need to update the site.

**Comment by diminoten** [comment]
Oh, looks like fantasypros does IDP like PPR/Half, so it'd be added as a 'format', and nothing passed in `positions`.

**Comment by jayjzheng** [comment]
that's probably because no IDP is worthy a top 200 pick?

**Comment by diminoten** [comment]
JJ Watt was 49th in scoring overall last year, and is definitely a top 200 pick.
