### ISSUE TITLE
Rankings are not updating.

### ISSUE THREAD

**Issue by danielstarman** [jayjzheng/ff_rankings#13]
I'm not sure if it's a bug on my side, but the rankings are not updating for me. Is there any way to force an update?

**Comment by jayjzheng** [comment]
how are you updating it?

**Comment by danielstarman** [comment]
This may be a case of me being stupid, I apologize. I thought that with the most recent commit and with Boris Chen going hourly, the rankings auto-updated. If you still do it manually, then there is no issue, and I apologize.
