### ISSUE TITLE
Can We Get an Update before Tonight?

### ISSUE THREAD

**Issue by kjs86z** [jayjzheng/ff_rankings#17]
Hi there,

First and foremost, I just wanted to thank you for making this draft helper tool.  I'm looking forward to using it tonight!

I know this is trivial as the overall rankings really won't change much, but the OCD in me would really like to see an update to Chen's tier list sometime this afternoon / early evening before my draft.

Not sure how labor intensive that may be...if its just a couple clicks, I'd really appreciate it!  

If not, it's most assuredly all good.  Thanks again for the time you've put into this.

- Kevin

**Comment by jayjzheng** [comment]
i have updated the workers to import every 4 hours instead of 12 starting 10:00am today.

should be good.

**Comment by kjs86z** [comment]
Cheers good sir!
