### ISSUE TITLE
Doc request: how do we set this up?

### ISSUE THREAD

**Issue by philip** [jayjzheng/ff_rankings#21]
Feature request: document how to install and set this up. 

Beyond 'bower install', it seems the referenced 'http://ff-api.herokuapp.com/' no longer exists (or is private, or I'm doing something wrong). What sort of data structure is used for us to create our own? Perhaps add an example of how you interact with imported data from fantasy pros and borischen.

**Comment by jayjzheng** [comment]
sorry, i didn't update the the URL in the repo, it should now point to `https://draftaid-api.herokuapp.com/`

**Comment by philip** [comment]
Thanks, everything works now :)
