### ISSUE TITLE
Colouring in Draft Aid for PPR/0.5 PPR

### ISSUE THREAD

**Issue by smc0407** [jayjzheng/ff_rankings#6]
The colouring for the tiers is a little wonky when you switch to either of the PPR options in Draft Aid. This specifically can be seen in the T.E. column, where Tiers 1, 5, and 9 (which happened to encompass the first 4 TEs) are all green. I think something happened to the pink colour highlighting...

**Comment by jayjzheng** [comment]
i can live with the rotating of 4 colors.
