### ISSUE TITLE
Update data for next season?

### ISSUE THREAD

**Issue by soccercjs2** [jayjzheng/ff_rankings#7]
Are you going to update the application so that it uses this year's rankings?

**Comment by jayjzheng** [comment]
yup, that's the plan. gonna need to get in touch with boris chen.

**Comment by connerT** [comment]
I'm curious how you get the json data from FantasyPros. I didn't see any way of exporting their data in json format. Did you construct it yourself? This helped me a ton during my draft last year. Thanks!

**Comment by jayjzheng** [comment]
I have a backend that serves the JSON content. I think it has functionality to import excel or csv. I don't get data directly from FantasyPros. I get it from Boris Chen who had it in a google spreadsheet.

**Comment by willoffire** [comment]
This past season i used your tool and fantasyfootballcalculator.com's ADP rankings to draft. I used them in 3 leagues (2 14 team leagues and a 10 team league). I won a 14 team league however I picked up ODB which had a lot to do with it, but i also dominated (1st all year, most points/gm, most total points etc.). I went to the championship in the 10 teamer with little lineup tinkering; few waiver adds/trades. In the other 14 teamer I started poorly and began dropping and trading players by wk 5. I later realized the players i lost performed well later in the season. I might have gone further in to the playoffs if I hadn't made those moves.

All in all, pretty successful year using your tool and I hope to use it again. I found that with each draft I did I was using ffcalc less and your tool more. By the 3rd draft I was using your tool exclusively.

**Comment by jayjzheng** [comment]
updated.

**Comment by soccercjs2** [comment]
It's looking great, already used it a couple times. Great job!

On Tue, Aug 4, 2015 at 4:34 PM, Jay Zheng <notifications@github.com> wrote:

> updated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jayjzheng/ff_rankings/issues/7#issuecomment-127796567>
> .
>



-- 
Collin Steranka
