### ISSUE TITLE
Draft grades don't make sense for first few picks/rounds.

### ISSUE THREAD

**Issue by wilsongee** [jayjzheng/ff_rankings#8]
Given the first pick, you will never receive a grade higher than a C, because your pick will at best fall in line with the consensus pick at that position. This will continue for a finite set of picks, possibly going for a long time if a particular league follows "chalk".

An example would be If I was given the first pick and I selected AP. Why is that graded as a C? That doesn't logically make sense. I would consider a co-efficient equal to the round in addition to the diff between rank and actual selection to weigh consensus picks higher in the earlier rounds.

**Comment by jayjzheng** [comment]
totally agree. the grades are pretty meaningless now. I will try to figure something out. otherwise, will simply remove it.

**Comment by wilsongee** [comment]
I don't think it's completely meaningless. If you get to the sixth round and there is a player that is still there, that would result in an A grade. I think if we weighed each round with a co-efficient, that would make grading on higher rounds more exact.

Maybe I can figure something out by looking into the Grading plugin. It's possible that it's already supporting some sort of weighed score.

**Comment by jayjzheng** [comment]
i am not using a plugin. it's here: https://github.com/jayjzheng/ff_rankings/blob/master/app/js/services/draft_aid.js

**Comment by wilsongee** [comment]
Cool. When I get some free time, I'll play around with it.

**Comment by itmustbejj** [comment]
I think C is fine for round one. It says "You took a player at the proper ADP for that pick." A grade of "C" says you did what you were supposed to. There is no value at the front, there are simply top tier players, and the picks that correlate within that tier. Value is introduced when you have the option to pick a higher tier than your pick should allow.
