### ISSUE TITLE
D/ST and Kicker Ratings?

### ISSUE THREAD

**Issue by Scorp2b1** [jayjzheng/ff_rankings#9]
Hi there,

LOVE this tool! Seriously. My question is that it seems as if only a few D/ST's come up in the search (Seattle, Buffalo) and no kickers are listed. Any idea as to why this is?

Thanks so much for the work you put into this! I'm in heaven.
Jonathan

**Comment by jayjzheng** [comment]
probably because none of the other D/ST and Kickers made the top 200 list?

**Comment by Scorp2b1** [comment]
Oh, I see. It's based on the Top 200. Thanks for the reply!
